version: "3.3"

services:
    nginx:
        image: nginx:1.20.0-alpine
        container_name: nginx
        volumes:
            - .:/docker
            - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./etc/nginx/logs:/etc/nginx/logs
        ports:
            - "80:80"
            - "443:443"

    php:
        # image: php:8.0.5-fpm
        build:
            context: .
            dockerfile: Dockerfile.php # 별도의 Dockerfile 로 이미지를 생성하고, mysqli extension 설치를 하기 때문에 'Dockerfile' 로 작업한다.
        container_name: php
        volumes:
            - .:/docker
            - ./etc/php.ini:/usr/local/etc/php/php.ini

    mariadb:
        image: mariadb:latest
        container_name: mariadb
        environment:
            - MYSQL_DATABASE=mydb # 처음 이미지 생성 후 컨테이너 실행 시 DB를 준비한다. 덮어쓰진 않음.
            - MYSQL_USER=myuser # 사용자를 지정.
            - MYSQL_PASSWORD=myroot12345 # 사용자 비밀번호.
            - MYSQL_ROOT_PASSWORD=myroot12345 # 관리자 비밀번호.
        volumes:
            - ./var/lib/mysql:/var/lib/mysql
        ports:
            - "3306:3306"

    phpmyadmin:
        image: phpmyadmin
        container_name: phpmyadmin
        restart: always
        ports:
            - 33060:80
        environment:
            - PMA_ARBITRARY=1
