version: '3.3'

services:
  nginx:
    image: nginx:1.20.0-alpine
    container_name: nginx-container
    volumes:
      - .:/docker
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/etc/nginx/logs
    ports:
      - "80:80"

  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: php-container
    volumes:
      - .:/docker
      - ./php.ini:/user/local/etc/php.php.ini

  mariadb:
    image: mariadb:latest
    container_name: mariadb-container
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=pass123
      - MYSQL_ROOT_PASSWORD=pass123
    volumes:
      - ./var/lib/mysql:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 33060:80
    environment:
      - PMA_ARBITRARY=1
