version: '3.3'

services:
  nginx:
    image: nginx:1.20.0-alpine
    container_name: nginx-container
    volumes:
      - .:/docker
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/etc/nginx/logs
    ports:
      - "80:80"

  php:
    image: php:8.0.6-fpm
    container_name: php-container
    volumes:
      - .:/docker
      - ./php.ini:/user/local/etc/php.php.ini

  mariadb:
    image: mariadb:latest
    container_name: mariadb-container
