version: '3.3'

services:
 nginx:
  image: nginx:1.20.0-alpine
  container_name: nginxCompose
  volumes:
   - .:/docker
   #- ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
   #- ./etc/nginx/logs:/etc/nginx/logs
  ports:
   - "80:80" 
   - "8000:80" 
   - "8001:80" 
